# Generated by Django 6.0.4 on 2026-04-25 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('balance_cached', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('import_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DRY_RUN', 'Dry Run'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_jobs', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('entity_type', models.CharField(choices=[('CLIENT', 'Client'), ('LEDGER_ENTRY', 'Ledger Entry')], max_length=32)),
                ('dedupe_key', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('DUPLICATE', 'Duplicate'), ('ERROR', 'Error')], max_length=16)),
                ('message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ledger.importjob')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('folder_no', models.CharField(blank=True, max_length=64)),
                ('stage', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tm_no', models.CharField(blank=True, db_index=True, max_length=64)),
                ('class_no', models.CharField(blank=True, max_length=16)),
                ('details', models.TextField(blank=True)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('entry_type', models.CharField(choices=[('NORMAL', 'Normal'), ('RECEIVED', 'Received'), ('OPENING', 'Opening')], default='NORMAL', max_length=16)),
                ('balance_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'code'], name='ledger_clie_company_15c39d_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_client_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['company', 'created_at'], name='ledger_impo_company_36b7a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.UniqueConstraint(fields=('company', 'import_hash'), name='uniq_import_hash_per_company'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['job', 'row_number'], name='ledger_impo_job_id_ad08be_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['job', 'status'], name='ledger_impo_job_id_7be987_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'client', 'date'], name='ledger_ledg_company_3b35ec_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'stage'], name='ledger_ledg_company_ca2643_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'tm_no'], name='ledger_ledg_company_c5533b_idx'),
        ),
    ]
